name = "dd-otel-traces"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]
logpush = true

[observability.logs]
enabled = true

[vars]
OTEL_SERVICE_NAME = "dd-otel-traces"
OTEL_SERVICE_VERSION = "1.0.0"
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "https://trace.agent.datadoghq.com/api/v0.2/traces"
OTEL_EXPORTER_OTLP_TRACES_HEADERS = "{\"dd-protocol\":\"otlp\", \"dd-otlp-source\":\"datadog\"}"